apiVersion: apps/v1
kind: Deployment
metadata:
  name: cianaadminapi-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cianaadminapi
  template:
    metadata:
      labels:
        app: cianaadminapi
    spec:
      containers:
      - name: cianaadminapi-service
        image: cianadevregistry.azurecr.io/cianaadminapi:v1
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: cianaadminapi-config

---
apiVersion: v1
kind: Service
metadata:
  name: cianaadminapi-service
spec:
  type: ClusterIP
  selector:
    app: cianaadminapi
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP

