apiVersion: apps/v1
kind: Deployment
metadata:
  name: cianaadminui-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cianaadminui
  template:
    metadata:
      labels:
        app: cianaadminui
    spec:
      containers:
      - name: cianaadminui
        image: cianadevregistry.azurecr.io/cianaadmin:v1
        ports:
        - containerPort: 4200
---
apiVersion: v1
kind: Service
metadata:
  name: cianaadminui-service
spec:
  type: ClusterIP
  ports:
  - port: 4200
    targetPort: 4200
    protocol: TCP
  selector:
    app: cianaadminui
