apiVersion: apps/v1
kind: Deployment
metadata:
  name: cianahealthapi-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cianahealthapi
  template:
    metadata:
      labels:
        app: cianahealthapi
    spec:
      containers:
      - name: cianahealthapi-service
        image: cianadevregistry.azurecr.io/cianahealthapi:v1
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: cianahealthapi-config

---
apiVersion: v1
kind: Service
metadata:
  name: cianahealthapi-service
spec:
  type: ClusterIP
  selector:
    app: cianahealthapi
  ports:
  - port: 8080
    targetPort: 8080
    name: http

