apiVersion: apps/v1
kind: Deployment
metadata:
  name: cianaclinicui-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cianaclinicui
  template:
    metadata:
      labels:
        app: cianaclinicui
    spec:
      containers:
      - name: cianaclinicui
        image: cianadevregistry.azurecr.io/cianaclinicui:v2
        ports:
        - containerPort: 4200
---
apiVersion: v1
kind: Service
metadata:
  name: cianaclinicui-service
spec:
  type: LoadBalancer
  ports:
  - port: 4200
    targetPort: 4200
    name: http
  selector:
    app: cianaclinicui
