apiVersion: apps/v1
kind: Deployment
metadata:
  name: cianaclinicapi-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cianaclinicapi
  template:
    metadata:
      labels:
        app: cianaclinicapi
    spec:
      containers:
      - name: cianaclinicapi
        image: cianadevregistry.azurecr.io/cianaclinicapi:v3
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: cianaclinicapi-config
---
apiVersion: v1
kind: Service
metadata:
  name: cianaclinicapi-service
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: cianaclinicapi
