apiVersion: apps/v1
kind: Deployment
metadata:
  name: cianaarexui-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cianaarexui
  template:
    metadata:
      labels:
        app: cianaarexui
    spec:
      containers:
      - name: cianaarexui
        image: cianadevregistry.azurecr.io/cianaarex:2
        ports:
        - containerPort: 4200
---
apiVersion: v1
kind: Service
metadata:
  name: cianaarexui-service
spec:
  type: ClusterIP
  ports:
  - port: 4200
    targetPort: 4200
    protocol: TCP
  selector:
    app: cianaarexui
