apiVersion: apps/v1
kind: Deployment
metadata:
  name: cianaarexapi-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cianaarexapi
  template:
    metadata:
      labels:
        app: cianaarexapi
    spec:
      containers:
      - name: api-service
        image: cianadevregistry.azurecr.io/cianaarexapi:v1
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: cianaarexapi-config

---
apiVersion: v1
kind: Service
metadata:
  name: cianaarexapi-service
spec:
  type: ClusterIP
  selector:
    app: cianaarexapi
  ports:
  - port: 8080
    targetPort: 8080
    name: http

