apiVersion: apps/v1
kind: Deployment
metadata:
  name: cianaaiapi-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cianaaiapi
  template:
    metadata:
      labels:
        app: cianaaiapi
    spec:
      containers:
      - name: cianaaiapi
        image: cianadevregistry.azurecr.io/cianaaiapi:v1
        ports:
        - containerPort: 4200
---
apiVersion: v1
kind: Service
metadata:
  name: cianaaiapi-service
spec:
  type: LoadBalancer
  ports:
  - port: 4200
    targetPort: 4200
    name: http
  selector:
    app: cianaaiapi
